apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-2
spec:
  selector:
    matchLabels:
      app: web-2
  replicas: 1
  template:
    metadata:
      labels:
        app: web-2
    spec:
      containers:
      - name: web-2
        image: nginx
