apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rroyhere/gitops-argocd.git
    targetRevision: HEAD
    path: ./declarative/manifests/web-2
   
  destination:
    server: https://kubernetes.default.svc
    namespace: web2

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
